on: push

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - uses: actions/cache@v3
        with:
          path: |
            ~/.konan
          key: ${{ hashFiles('build.gradle.kts') }}


      - run: ./gradlew publishToMavenLocal

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '/home/runner/.m2/repository'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
